#!/usr/bin/env bash
# A Bash script that loops forever, handles SIGTERM, and prints a defiant message
trap 'echo "I am invincible!!!"' TERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
