#!/usr/bin/env bash
# Prints "To infinity and beyond" forever and prints "I am invincible!!!" when receiving SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
