#!/usr/bin/env bash
# This script handles SIGTERM signal and continues running
handle_signal() {
    echo "I am invincible!!!"
}
trap handle_signal TERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
